version: "3.9"
services:
    server:
        build: server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app/
    client:
        build: client
        ports:
            - "80:8080"
        volumes:
            - ./client/src:/usr/src/app/src
        environment:
            - CHOKIDAR_USEPOLLING=true
volumes:
    mongo_data:
