version: "3.9"
services:
    server:
        build: server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app/
    client:
        build: client
        ports:
            - "80:8080"
        volumes:
            - ./client/src:/usr/src/app/src
    database:
        image: "mongo:4.2"
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
volumes:
    mongo_data:
